//Action types

export const LIST_API_REQUEST = 'LIST_API_REQUEST';
export const LIST_API_RECEIVE = 'LIST_API_RECEIVE';
export const LIST_API_ERROR = 'LIST_API_ERROR';
export const LIST_API_RESET = 'LIST_API_RESET';

//Get sector 
export const SECTOR_API_REQUEST = 'SECTOR_API_REQUEST';
export const SECTOR_API_RECEIVE = 'SECTOR_API_RECEIVE';
export const SECTOR_API_ERROR = 'SECTOR_API_ERROR';

//Get quotes
export const QUOTES_DATA_REQUEST = 'QUOTES_DATA_REQUEST';
export const QUOTES_DATA_RECEIVE = 'QUOTES_DATA_RECEIVE';
export const QUOTES_DATA_ERROR = 'QUOTES_DATA_ERROR';

//Mercado
export const CHANGE_MERCADO = 'CHANGE_MERCADO';

//Follow list
export const POST_FOLLOW_REQUEST = 'POST_FOLLOW_REQUEST';
export const POST_FOLLOW_RECEIVE = 'POST_FOLLOW_RECEIVE';
export const POST_FOLLOW_ERROR = 'POST_FOLLOW_ERROR';

//Search company
export const SEARCH_COMPANY_REQUEST = 'SEARCH_COMPANY_REQUEST';
export const SEARCH_COMPANY_RECEIVE = 'SEARCH_COMPANY_RECEIVE';
export const SEARCH_COMPANY_ERROR = 'SEARCH_COMPANY_ERROR';

//SEARCH MONITOR
export const GET_MONITOR_REQUEST = 'GET_MONITOR_REQUEST';
export const GET_MONITOR_RECEIVE = 'GET_MONITOR_RECEIVE';
export const GET_MONITOR_ERROR = 'GET_MONITOR_ERROR';

//CREAR ALERT
export const PUT_ALERT_REQUEST_VARIACION = 'PUT_ALERT_REQUEST_VARIACION';
export const PUT_ALERT_REQUEST_PRECIO = 'PUT_ALERT_REQUEST_PRECIO';
export const PUT_ALERT_REQUEST_RANGO = 'PUT_ALERT_REQUEST_PRECIO';
export const PUT_ALERT_REQUEST_NOTICIA = 'PUT_ALERT_REQUEST_NOTICIA';
export const PUT_ALERT_RECEIVE = 'PUT_ALERT_RECEIVE';
export const PUT_ALERT_ERROR = 'PUT_ALERT_ERROR';

//Get alert
export const GET_ALERT_REQUEST='GET_ALERT_REQUEST';
export const GET_ALERT_RECEIVE = 'GET_ALERT_RECEIVE';
export const GET_ALERT_ERROR = 'GET_ALERT_ERROR';


//BURS
export const GET_BURS_REQUEST = 'GET_BURS_REQUEST';
export const GET_BURS_RECIEVE = 'GET_BURS_RECIEVE';
export const GET_BURS_ERROR = 'GET_BURS_ERROR';

//DELETE
export const DELETE_ALERT_REQUEST = 'DELETE_ALERT_REQUEST';
export const DELETE_ALERT_RECEIVE = 'DELETE_ALERT_RECEIVE';
export const DELETE_ALERT_ERROR = 'DELETE_ALERT_ERROR';

//Post correo & celular para recuperar contraseña
export const POST_EMAIL_PHONE_SEND = 'POST_EMAIL_PHONE_REQUEST';
export const POST_EMAIL_PHONE_RECEIVE = 'POST_EMAIL_PHONE_RECEIVE';
export const POST_EMAIL_PHONE_ERROR = 'POST_EMAIL_PHONE_ERROR';

//Post recuperaValida
export const POST_RECUPERA_VALIDA_SEND = 'POST_RECUPERA_VALIDA_REQUEST';
export const POST_RECUPERA_VALIDA_RECEIVE = 'POST_RECUPERA_VALIDA_RECEIVE';
export const POST_RECUPERA_VALIDA_ERROR = 'POST_RECUPERA_VALIDA_ERROR';

//Post recuperaActualiza

export const POST_RECUPERA_ACTUALIZA_SEND = 'POST_RECUPERA_ACTUALIZA_REQUEST';
export const POST_RECUPERA_ACTUALIZA_RECEIVE = 'POST_RECUPERA_ACTUALIZA_RECEIVE';
export const POST_RECUPERA_ACTUALIZA_ERROR = 'POST_RECUPERA_ACTUALIZA_ERROR';

//PasswordPost
export const POST_PASSWORDPOST_SEND = 'POST_PASSWORDPOST_REQUEST';
export const POST_PASSWORDPOST_RECEIVE = 'POST_PASSWORDPOST_RECEIVE';
export const POST_PASSWORDPOST_ERROR = 'POST_PASSWORDPOST_ERROR';

//PasswordGET

export const GET_PASSWORDGET_REQUEST='GET_PASSWORDGET_REQUEST';
export const GET_PASSWORDGET_RECEIVE = 'GET_PASSWORDGET_RECEIVE';
export const GET_PASSWORDGET_ERROR = 'GET_PASSWORDGET_ERROR';
export const RESET_STATE_PASSWORD = 'RESET_STATE_PASSWORD' ;

//////////////////// Checked  ///////////////////////////////

//Get issuer from list
export const GET_LIST_ISSUER_REQUEST = 'GET_LIST_ISSUER_REQUEST';
export const GET_LIST_ISSUER_RECEIVE = 'GET_LIST_ISSUER_RECEIVE';
export const GET_LIST_ISSUER_ERROR = 'GET_LIST_ISSUER_ERROR';
export const GET_LIST_ISSUER_RESET = 'GET_LIST_ISSUER_RESET';

//Get users list: Regresa las listas que el usuario creó o sigue de las preestablecidas
export const LIST_USER_REQUEST = 'LIST_USER_REQUEST';
export const LIST_USER_RECEIVE = 'LIST_USER_RECEIVE';
export const LIST_USER_ERROR = 'LIST_USER_ERROR';

//Ge users Stations: Rregresa el nombre de las emisoras que el usuario sigue en sus listas
export const LIST_STATION_REQUEST = 'LIST_STATION_REQUEST';
export const LIST_STATION_RECEIVE = 'LIST_STATION_RECEIVE';
export const LIST_STATION_ERROR = 'LIST_STATION_ERROR';
    
//Post add issuer to list: Agregar emisora a una lista
export const POST_ISSUER_REQUEST = 'POST_ISSUER_REQUEST';
export const POST_ISSUER_RECEIVE = 'POST_ISSUER_RECEIVE';
export const POST_ISSUER_ERROR = 'POST_ISSUER_ERROR';

//Get list index: Trae las emisoras de un índice
export const LIST_INDEX_REQUEST = 'LIST_INDEX_REQUEST';
export const LIST_INDEX_RECEIVE = 'LIST_INDEX_RECEIVE';
export const LIST_INDEX_ERROR = 'LIST_INDEX_ERROR';

//Change user list name
export const CHANGE_LIST_REQUEST = 'CHANGE_LIST_REQUEST';
export const CHANGE_LIST_RECEIVE = 'CHANGE_LIST_RECEIVE';
export const CHANGE_LIST_ERROR = 'CHANGE_LIST_ERROR';

//Delete user list
export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_RECEIVE = 'DELETE_LIST_RECEIVE';
export const DELETE_LIST_ERROR = 'DELETE_LIST_ERROR';

//Delete issuer from a list
export const DELETE_ISSUER_REQUEST = 'DELETE_ISSUER_REQUEST';
export const DELETE_ISSUER_RECEIVE = 'DELETE_ISSUER_RECEIVE';
export const DELETE_ISSUER_ERROR = 'DELETE_ISSUER_ERROR';

//Unfollow list
export const DELETE_UNFOLLOW_REQUEST = 'DELETE_UNFOLLOW_REQUEST';
export const DELETE_UNFOLLOW_RECEIVE = 'DELETE_UNFOLLOW_RECEIVE';
export const DELETE_UNFOLLOW_ERROR = 'DELETE_UNFOLLOW_ERROR';

//PROFILE DATA
export const GET_PROFILE_REQUEST = 'GET_PROFILE_DATA';
export const GET_PROFILE_RECEIVE = 'GET_PROFILE_RECEIVE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

//Recomendaciones de emisoras
export const GET_RECOM_REQUEST = 'GET_RECOM_REQUEST';
export const GET_RECOM_RECEIVE = 'GET_RECOM_RECEIVE';
export const GET_RECOM_ERROR = 'GET_RECOM_ERROR';

//Get news
export const NEWS_API_REQUEST = 'NEWS_API_REQUEST';
export const NEWS_API_RECEIVE = 'NEWS_API_RECEIVE';
export const NEWS_API_ERROR = 'NEWS_API_ERROR';

//Get story news
export const STORY_API_REQUEST = 'STORY_API_REQUEST';
export const STORY_API_RECEIVE = 'STORY_API_RECEIVE';
export const STORY_API_ERROR = 'STORY_API_ERROR';

//Portfolio graph
export const GET_PORTFOLIO_REQUEST = 'GET_PORTFOLIO_REQUEST';
export const GET_PORTFOLIO_RECEIVE = 'GET_PORTFOLIO_RECEIVE';
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR';

//Resumen graph
export const GET_RESUMEN_REQUEST = 'GET_RESUMEN_REQUEST';
export const GET_RESUMEN_RECEIVE = 'GET_RESUMEN_RECEIVE';
export const GET_RESUMEN_ERROR = 'GET_RESUMEN_ERROR';

//Values portafolio
export const GET_VALUE_REQUEST = 'GET_VALUE_REQUEST';
export const GET_VALUE_RECEIVE = 'GET_VALUE_RECEIVE';
export const GET_VALUE_ERROR = 'GET_VALUE_ERROR';

//Tabla de Posiciones Portfolio Values
export const GET_POSITION_REQUEST = 'GET_POSITION_REQUEST'; 
export const GET_POSITION_RECEIVE = 'GET_POSITION_RECEIVE';
export const GET_POSITION_ERROR = 'GET_POSITION_ERROR';

//Post new list
export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_RECEIVE = 'POST_LIST_RECEIVE';
export const POST_LIST_ERROR = 'POST_LIST_ERROR';

//Get ordenes
export const GET_ORDENES_REQUEST = 'GET_ORDENES_REQUEST';
export const GET_ORDENES_RECEIVE = 'GET_ORDENES_RECEIVE';
export const GET_ORDENES_ERROR = 'GET_ORDENES_ERROR';

//Get movers
export const GET_MOVERS_REQUEST = 'GET_MOVERS_REQUEST';
export const GET_MOVERS_RECEIVE = 'GET_MOVERS_RECEIVE';
export const GET_MOVERS_ERROR = 'GET_MOVERS_ERROR';

//Get Consultas
export const GET_CONSULTAS_REQUEST = 'GET_CONSULTAS_REQUEST';
export const GET_CONSULTAS_RECEIVE = 'GET_CONSULTAS_RECEIVE';
export const GET_CONSULTAS_ERROR = 'GET_CONSULTAS_ERROR';

//Get operaciones Dia 
export const GET_OPERACIONESDIA_REQUEST = 'GET_OPERACIONESDIA_REQUEST';
export const GET_OPERACIONESDIA_RECEIVE = 'GET_OPERACIONESDIA_RECEIVE';
export const GET_OPERACIONESDIA_ERROR = 'GET_OPERACIONESDIA_ERROR';

//Multiple Ordenes
export const MULTIPLE_ORDERS = 'MULTIPLE_ORDERS';

// Multiple Compras
export const MULTIPLE_BUY_ADD = 'MULTIPLE_BUY_ADD';
export const MULTIPLE_BUY_DELETE = 'MULTIPLE_BUY_DELETE';
export const MULTIPLE_BUY_DELETE_ALL = 'MULTIPLE_BUY_DELETE_ALL';

//Post modificaciones a la orden del cliente
export const POST_ORDEN_REQUEST = 'POST_ORDEN_REQUEST';
export const POST_ORDEN_RECEIVE = 'POST_ORDEN_RECEIVE';
export const POST_ORDEN_ERROR = 'POST_ORDEN_ERROR';

//Get api folio recibes el folio de la tarjeta que le vas a pedir al cliente y la posición en la tarjeta que le vas a pedir
export const GET_FOLIO_REQUEST = 'GET_FOLIO_REQUEST';
export const GET_FOLIO_RECEIVE = 'GET_FOLIO_RECEIVE';
export const GET_FOLIO_ERROR = 'GET_FOLIO_ERROR';

//Post codigo de folio en la posicion que se pidio
export const POST_POSICION_FOLIO_REQUEST = 'POST_POSICION_FOLIO_REQUEST';
export const POST_POSICION_FOLIO_RECEIVE = 'POST_POSICION_FOLIO_RECEIVE';
export const POST_POSICION_FOLIO_ERROR = 'POST_POSICION_FOLIO_ERROR';

//Refinitiv recomendacion emisosar similares
export const GET_EMISORA_SIMILAR_REQUEST = 'GET_EMISORA_SIMILAR_REQUEST';
export const GET_EMISORA_SIMILAR_RECEIVE = 'GET_EMISORA_SIMILAR_RECEIVE';
export const GET_EMISORA_SIMILAR_ERROR = 'GET_EMISORA_SIMILAR_ERROR';

//GET Cartera
export const GET_CARTERA_REQUEST = "GET_CARTERA_REQUEST";
export const GET_CARTERA_RECEIVE = "GET_CARTERA_RECEIVE";
export const  GET_CARTERA_ERROR = "GET_CARTERA_ERROR";

// Get info de compra de ordenes 
export const GET_BUY_TRADE_DATA_REQUEST = 'GET_BUY_TRADE_DATA_REQUEST';
export const GET_BUY_TRADE_DATA_RECEIVE = 'GET_BUY_TRADE_DATA_RECEIVE';
export const GET_BUY_TRADE_DATA_ERROR = 'GET_BUY_TRADE_DATA_ERROR';

// Post compra de orden
export const POST_BUY_ISSUER_REQUEST = 'POST_BUY_ISSUER_REQUEST';
export const POST_BUY_ISSUER_RECEIVE = 'POST_BUY_ISSUER_RECEIVE';
export const POST_BUY_ISSUER_ERROR = 'POST_BUY_ISSUER_ERROR';

// Get info de venta de ordenes 
export const GET_SELL_TRADE_DATA_REQUEST = 'GET_SELL_TRADE_DATA_REQUEST';
export const GET_SELL_TRADE_DATA_RECEIVE = 'GET_SELL_TRADE_DATA_RECEIVE';
export const GET_SELL_TRADE_DATA_ERROR = 'GET_SELL_TRADE_DATA_ERROR';

// Post compra de orden
export const POST_SELL_ISSUER_REQUEST = 'POST_SELL_ISSUER_REQUEST';
export const POST_SELL_ISSUER_RECEIVE = 'POST_SELL_ISSUER_RECEIVE';
export const POST_SELL_ISSUER_ERROR = 'POST_SELL_ISSUER_ERROR';

//Get poder de compra
export const GET_PODER_COMPRA_REQUEST = 'GET_PODER_COMPRA_REQUEST';
export const GET_PODER_COMPRA_RECEIVE = 'GET_PODER_COMPRA_RECEIVE';
export const GET_PODER_COMPRA_ERROR = 'GET_PODER_COMPRA_ERROR';

// Post multiples compras de emisora
export const POST_MULT_BUY_ISSUER_REQUEST = 'POST_MULT_BUY_ISSUER_REQUEST';
export const POST_MULT_BUY_ISSUER_RECEIVE = 'POST_MULT_BUY_ISSUER_RECEIVE';
export const POST_MULT_BUY_ISSUER_ERROR = 'POST_MULT_BUY_ISSUER_ERROR';

// Post multiples ventas de emisora
export const POST_MULT_SELL_ISSUER_REQUEST = 'POST_MULT_SELL_ISSUER_REQUEST';
export const POST_MULT_SELL_ISSUER_RECEIVE = 'POST_MULT_SELL_ISSUER_RECEIVE';
export const POST_MULT_SELL_ISSUER_ERROR = 'POST_MULT_SELL_ISSUER_ERROR';

//Get emisoras que pueden hacer stoploss
export const GET_STOPLOSS_REQUEST = 'GET_STOPLOSS_REQUEST';
export const GET_STOPLOSS_RECEIVE = 'GET_STOPLOSS_RECEIVE';
export const GET_STOPLOSS_ERROR = 'GET_STOPLOSS_ERROR';

//Fondos Familias
export const GET_FONDOS_FAMILIAS_REQUEST = 'GET_FONDOS_FAMILIAS_REQUEST';
export const GET_FONDOS_FAMILIAS_RECEIVE = 'GET_FONDOS_FAMILIAS_RECEIVE';
export const GET_FONDOS_FAMILIAS_ERROR = 'GET_FONDOS_FAMILIAS_ERROR';

//Refinitiv Grafica
export const GET_REFINITIV_GRAFICA_REQUEST = 'GET_REFINITIV_GRAFICA_REQUEST';
export const GET_REFINITIV_GRAFICA_RECEIVE = 'GET_REFINITIV_GRAFICA_RECEIVE';
export const GET_REFINITIV_GRAFICA_ERROR = 'GET_REFINITIV_GRAFICA_ERROR';

//Fondos CPA EMIS
export const GET_FONDOS_CPAEMIS_REQUEST = 'GET_FONDOS_CPAEMIS_REQUEST';
export const GET_FONDOS_CPAEMIS_RECEIVE = 'GET_FONDOS_CPAEMIS_RECEIVE';
export const GET_FONDOS_CPAEMIS_ERROR = 'GET_FONDOS_CPAEMIS_ERROR';

//Fondos VTA EMIS
export const GET_FONDOS_VTAEMIS_REQUEST = 'GET_FONDOS_VTAEMIS_REQUEST';
export const GET_FONDOS_VTAEMIS_RECEIVE = 'GET_FONDOS_VTAEMIS_RECEIVE';
export const GET_FONDOS_VTAEMIS_ERROR = 'GET_FONDOS_VTAEMIS_ERROR';

//Fondos CPA GET
export const GET_FONDOS_CPA_REQUEST = 'GET_FONDOS_CPA_REQUEST';
export const GET_FONDOS_CPA_RECEIVE = 'GET_FONDOS_CPA_RECEIVE';
export const GET_FONDOS_CPA_ERROR = 'GET_FONDOS_CPA_ERROR';

//Fondos CPA PUT
export const PUT_FONDOS_CPA_REQUEST = 'PUT_FONDOS_CPA_REQUEST';
export const PUT_FONDOS_CPA_RECEIVE = 'PUT_FONDOS_CPA_RECEIVE';
export const PUT_FONDOS_CPA_ERROR = 'PUT_FONDOS_CPA_ERROR';

//Fondos VTA GET
export const GET_FONDOS_VTA_REQUEST = 'GET_FONDOS_VTA_REQUEST';
export const GET_FONDOS_VTA_RECEIVE = 'GET_FONDOS_VTA_RECEIVE';
export const GET_FONDOS_VTA_ERROR = 'GET_FONDOS_VTA_ERROR';

//Fondos VTA PUT
export const PUT_FONDOS_VTA_REQUEST = 'PUT_FONDOS_VTA_REQUEST';
export const PUT_FONDOS_VTA_RECEIVE = 'PUT_FONDOS_VTA_RECEIVE';
export const PUT_FONDOS_VTA_ERROR = 'PUT_FONDOS_VTA_ERROR';
//Commodities
export const GET_COMMODITIES_REQUEST = 'GET_COMMODITIES_REQUEST';
export const GET_COMMODITIES_RECEIVE = 'GET_COMMODITIES_RECEIVE';
export const GET_COMMODITIES_ERROR = 'GET_COMMODITIES_ERROR';

//Posturas emisora
export const GET_POSTURAS_REQUEST = 'GET_POSTURAS_REQUEST';
export const GET_POSTURAS_RECEIVE = 'GET_POSTURAS_RECEIVE';
export const GET_POSTURAS_ERROR = 'GET_POSTURAS_ERRROR';

//Get ordenes emisora
export const GET_ORDENES_ISSUER_REQUEST = 'GET_ORDENES_ISSUER_REQUEST';
export const GET_ORDENES_ISSUER_RECEIVE = 'GET_ORDENES_ISSUER_RECEIVE';
export const GET_ORDENES_ISSUER_ERROR = 'GET_ORDENES_ISSUER_ERROR';

// Modal Compra / Venta
export const COMPRA = 'COMPRA';
export const VENTA = 'VENTA';

//Get data_opfondos_1.xml, info de todos los fondos
export const GET_DATA_OPFONDOS_XML_REQUEST = 'GET_DATA_OPFONDOS_XML_REQUEST';
export const GET_DATA_OPFONDOS_XML_RECEIVE = 'GET_DATA_OPFONDOS_XML_RECEIVE';
export const GET_DATA_OPFONDOS_XML_ERROR = 'GET_DATA_OPFONDOS_XML_ERROR';

//Post login object
export const POST_LOGIN_OBJECT_REQUEST = 'POST_LOGIN_OBJECT_REQUEST';
export const POST_LOGIN_OBJECT_RECEIVE = 'POST_LOGIN_OBJECT_RECEIVE';
export const POST_LOGIN_OBJECT_ERROR = 'POST_LOGIN_OBJECT_ERROR';
export const POST_LOGIN_OBJECT_LOGOUT = 'POST_LOGIN_OBJECT_LOGOUT'; //para borrar el obj de login

//Post logout api
export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST';
export const POST_LOGOUT_RECEIVE = 'POST_LOGOUT_RECEIVE';
export const POST_LOGOUT_ERROR = 'POST_LOGOUT_ERROR';

// Catalogo de lista de emisoras
export const GET_CATALOGO_LISTA_EMISORAS_REQUEST = 'GET_CATALOGO_LISTA_EMISORAS_REQUEST';
export const GET_CATALOGO_LISTA_EMISORAS_RECEIVE = 'GET_CATALOGO_LISTA_EMISORAS_RECEIVE';
export const GET_CATALOGO_LISTA_EMISORAS_ERROR = 'GET_CATALOGO_LISTA_EMISORAS_ERROR';

//Posicion en emisora
export const GET_INFO_EMISORA_REQUEST = 'GET_INFO_EMISORA_REQUEST';
export const GET_INFO_EMISORA_RECEIVE = 'GET_INFO_EMISORA_RECEIVE';
export const GET_INFO_EMISORA_ERROR = 'GET_INFO_EMISORA_ERROR';

// Catalogo completo de emisoras
export const GET_CATALOGO_EMISORAS_REQUEST = 'GET_CATALOGO_EMISORAS_REQUEST';
export const GET_CATALOGO_EMISORAS_RECEIVE = 'GET_CATALOGO_EMISORAS_RECEIVE';
export const GET_CATALOGO_EMISORAS_ERROR = 'GET_CATALOGO_EMISORAS_ERROR';

// GET CONSULTA SALDOS
export const GET_CONSULTA_SALDOS_REQUEST = 'GET_CONSULTA_SALDOS_REQUEST';
export const GET_CONSULTA_SALDOS_RECEIVE = 'GET_CONSULTA_SALDOS_RECEIVE';
export const GET_CONSULTA_SALDOS_ERROR = 'GET_CONSULTA_SALDOS_ERROR';

// GET DEPOSITO BANCOS
export const GET_DEPOSITO_BANCOS_REQUEST = 'GET_DEPOSITO_BANCOS_REQUEST';
export const GET_DEPOSITO_BANCOS_RECEIVE = 'GET_DEPOSITO_BANCOS_RECEIVE';
export const GET_DEPOSITO_BANCOS_ERROR = 'GET_DEPOSITO_BANCOS_ERROR';

// POST DEPOSITO
export const POST_DEPOSITO_REQUEST = 'POST_DEPOSITO_REQUEST';
export const POST_DEPOSITO_RECEIVE = 'POST_DEPOSITO_RECEIVE';
export const POST_DEPOSITO_ERROR = 'POST_DEPOSITO_ERROR';

// GET RETIRO INFO
export const GET_RETIRO_INFO_REQUEST = 'GET_RETIRO_INFO_REQUEST';
export const GET_RETIRO_INFO_RECEIVE = 'GET_RETIRO_INFO_RECEIVE';
export const GET_RETIRO_INFO_ERROR = 'GET_RETIRO_INFO_ERROR';

// POST RETIRO
export const POST_RETIRO_REQUEST = 'POST_RETIRO_REQUEST';
export const POST_RETIRO_RECEIVE = 'POST_RETIRO_RECEIVE';
export const POST_RETIRO_ERROR = 'POST_RETIRO_ERROR';

// GET EMAIL
export const GET_EMAIL_REQUEST = 'GET_EMAIL_REQUEST';
export const GET_EMAIL_RECEIVE = 'GET_EMAIL_RECEIVE';
export const GET_EMAIL_ERROR = 'GET_EMAIL_ERROR';

// PUT EMAIL
export const PUT_EMAIL_REQUEST = 'PUT_EMAIL_REQUEST';
export const PUT_EMAIL_RECEIVE = 'PUT_EMAIL_RECEIVE';
export const PUT_EMAIL_ERROR = 'PUT_EMAIL_ERROR';

// POST EMAIL
export const POST_EMAIL_REQUEST = 'POST_EMAIL_REQUEST';
export const POST_EMAIL_RECEIVE = 'POST_EMAIL_RECEIVE';
export const POST_EMAIL_ERROR = 'POST_EMAIL_ERROR';

// GET CELULAR
export const GET_CELULAR_REQUEST = 'GET_CELULAR_REQUEST';
export const GET_CELULAR_RECEIVE = 'GET_CELULAR_RECEIVE';
export const GET_CELULAR_ERROR = 'GET_CELULAR_ERROR';

// PUT CELULAR
export const PUT_CELULAR_REQUEST = 'PUT_CELULAR_REQUEST';
export const PUT_CELULAR_RECEIVE = 'PUT_CELULAR_RECEIVE';
export const PUT_CELULAR_ERROR = 'PUT_CELULAR_ERROR';

// POST CELULAR
export const POST_CELULAR_REQUEST = 'POST_CELULAR_REQUEST';
export const POST_CELULAR_RECEIVE = 'POST_CELULAR_RECEIVE';
export const POST_CELULAR_ERROR = 'POST_CELULAR_ERROR';

// PUT CELULAR REENVIA
export const PUT_CELULAR_REENVIA_REQUEST = 'PUT_CELULAR_REENVIA_REQUEST';
export const PUT_CELULAR_REENVIA_RECEIVE = 'PUT_CELULAR_REENVIA_RECEIVE';
export const PUT_CELULAR_REENVIA_ERROR = 'PUT_CELULAR_REENVIA_ERROR';

//Fondos Monitor
export const GET_FONDOS_MONITOR_REQUEST = 'GET_FONDOS_MONITOR_REQUEST';
export const GET_FONDOS_MONITOR_RECEIVE = 'GET_FONDOS_MONITOR_RECEIVE';
export const GET_FONDOS_MONITOR_ERROR = 'GET_FONDOS_MONITOR_ERROR';

//Get acumulado
export const GET_ACUMULADO_REQUEST='GET_ACUMULADO_REQUEST';
export const GET_ACUMULADO_RECEIVE = 'GET_ACUMULADO_RECEIVE';
export const GET_ACUMULADO_ERROR = 'GET_ACUMULADO_ERROR';

//Get hechos
export const GET_HECHOS_REQUEST='GET_HECHOS_REQUEST';
export const GET_HECHOS_RECEIVE = 'GET_HECHOS_RECEIVE';
export const GET_HECHOS_ERROR = 'GET_HECHOS_ERROR';

// POST Stop Loss
export const POST_STOPLOSS_REQUEST = 'POST_STOPLOSS_REQUEST';
export const POST_STOPLOSS_RECEIVE = 'POST_STOPLOSS_RECEIVE';
export const POST_STOPLOSS_ERROR = 'POST_STOPLOSS_ERROR';

// GET Fondos Estrategia Integral
export const GET_FONDOS_ESTRATEGIA_INTEGRAL_REQUEST = 'GET_FONDOS_ESTRATEGIA_INTEGRAL_REQUEST';
export const GET_FONDOS_ESTRATEGIA_INTEGRAL_RECEIVE = 'GET_FONDOS_ESTRATEGIA_INTEGRAL_RECEIVE';
export const GET_FONDOS_ESTRATEGIA_INTEGRAL_ERROR = 'GET_FONDOS_ESTRATEGIA_INTEGRAL_ERROR';

// GET Fondos Distribucion
export const GET_FONDOS_FAM_DISTRIBUCION_REQUEST = 'GET_FONDOS_FAM_DISTRIBUCION_REQUEST';
export const GET_FONDOS_FAM_DISTRIBUCION_RECEIVE = 'GET_FONDOS_FAM_DISTRIBUCION_RECEIVE';
export const GET_FONDOS_FAM_DISTRIBUCION_ERROR = 'GET_FONDOS_FAM_DISTRIBUCION_ERROR';

//Fondos NUEVA Familias
export const GET_FONDOS_NUEVA_FAMILIAS_REQUEST = 'GET_FONDOS_NUEVA_FAMILIAS_REQUEST';
export const GET_FONDOS_NUEVA_FAMILIAS_RECEIVE = 'GET_FONDOS_NUEVA_FAMILIAS_RECEIVE';
export const GET_FONDOS_NUEVA_FAMILIAS_ERROR = 'GET_FONDOS_NUEVA_FAMILIAS_ERROR';

//Get historico
export const GET_HISTORICO_REQUEST='GET_HISTORICO_REQUEST';
export const GET_HISTORICO_RECEIVE = 'GET_HISTORICO_RECEIVE';
export const GET_HISTORICO_ERROR = 'GET_HISTORICO_ERROR';

//Cambio de filtro en la graf de historico
export const SEND_PORTAFOLIO_VALUE = 'SEND_PORTAFOLIO_VALUE';

//Catalogo de emisoras para trading
export const GET_CATALOGO_TRADING_REQUEST = 'GET_CATALOGO_TRADING_REQUEST';
export const GET_CATALOGO_TRADING_RECEIVE = 'GET_CATALOGO_TRADING_RECEIVE';
export const GET_CATALOGO_TRADING_ERROR = 'GET_CATALOGO_TRADING_ERROR';

//Historial
export const GET_HISTORIALEMISORA_REQUEST = 'GET_HISTORIALEMISORA_REQUEST';
export const GET_HISTORIALEMISORA_RECEIVE = 'GET_HISTORIALEMISORA_RECEIVE';
export const GET_HISTORIALEMISORA_ERROR = 'GET_HISTORIALEMISORA_ERROR';
//Saber el state en el que se encuentra el websocket
export const GET_READYSTATE_REQUEST = 'GET_READYSTATE_REQUEST';
export const GET_READYSTATE_RECEIVE = 'GET_READYSTATE_RECEIVE';
export const GET_READYSTATE_ERROR = 'GET_READYSTATE_ERROR';

// GET config de vector analisis
export const GET_CONFIG_VA_REQUEST = 'GET_CONFIG_VA_REQUEST';
export const GET_CONFIG_VA_RECEIVE = 'GET_CONFIG_VA_RECEIVE';
export const GET_CONFIG_VA_ERROR = 'GET_CONFIG_VA_ERROR';
//Get Pregunta Secreta Api
export const GET_PREGUNTA_SECRETA_REQUEST = 'GET_PREGUNTA_SECRETA_REQUEST';
export const GET_PREGUNTA_SECRETA_RECEIVE = 'GET_PREGUNTA_SECRETA_RECEIVE';
export const GET_PREGUNTA_SECRETA_ERROR = 'GET_PREGUNTA_SECRETA_ERROR';

//Post Pregunta Secreta Api
export const POST_PREGUNTA_SECRETA_REQUEST = 'POST_PREGUNTA_SECRETA_REQUEST';
export const POST_PREGUNTA_SECRETA_RECEIVE = 'POST_PREGUNTA_SECRETA_RECEIVE';
export const POST_PREGUNTA_SECRETA_ERROR = 'POST_PREGUNTA_SECRETA_ERROR';

//Resetear reducers relacionados a pregunta secreta
export const RESET_STATE_PREGUNTA_SECRETA = 'RESET_STATE_PREGUNTA_SECRETA';
/*
    estos reducers regresan a su initial state cuando 
    ocurre la action RESET_STATE_PREGUNTA_SECRETA:
        - getPreguntaSecretaReducer
        - postPreguntaSecretaReducer
*/

//Get Alertas Evento
export const GET_ALERTAS_EVENTO_REQUEST = 'GET_ALERTAS_EVENTO_REQUEST';
export const GET_ALERTAS_EVENTO_RECEIVE = 'GET_ALERTAS_EVENTO_RECEIVE';
export const GET_ALERTAS_EVENTO_ERROR = 'GET_ALERTAS_EVENTO_ERROR';

//Get Alertas Volatilidad
export const GET_ALERTAS_VOLATILIDAD_REQUEST = 'GET_ALERTAS_VOLATILIDAD_REQUEST';
export const GET_ALERTAS_VOLATILIDAD_RECEIVE = 'GET_ALERTAS_VOLATILIDAD_RECEIVE';
export const GET_ALERTAS_VOLATILIDAD_ERROR = 'GET_ALERTAS_VOLATILIDAD_ERROR';

//Post Alertas Evento Alta
export const POST_ALERTAS_EVENTO_ALTA_REQUEST = 'POST_ALERTAS_EVENTO_ALTA_REQUEST';
export const POST_ALERTAS_EVENTO_ALTA_RECEIVE = 'POST_ALERTAS_EVENTO_ALTA_RECEIVE';
export const POST_ALERTAS_EVENTO_ALTA_ERROR = 'POST_ALERTAS_EVENTO_ALTA_ERROR';

//Post Alertas Evento Alta
export const POST_ALERTAS_VOLATILIDAD_ALTA_REQUEST = 'POST_ALERTAS_VOLATILIDAD_ALTA_REQUEST';
export const POST_ALERTAS_VOLATILIDAD_ALTA_RECEIVE = 'POST_ALERTAS_VOLATILIDAD_ALTA_RECEIVE';
export const POST_ALERTAS_VOLATILIDAD_ALTA_ERROR = 'POST_ALERTAS_VOLATILIDAD_ALTA_ERROR';

//DELETE Alertas Evento Baja
export const DELETE_ALERTAS_EVENTO_BAJA_REQUEST = 'DELETE_ALERTAS_EVENTO_BAJA_REQUEST';
export const DELETE_ALERTAS_EVENTO_BAJA_RECEIVE = 'DELETE_ALERTAS_EVENTO_BAJA_RECEIVE';
export const DELETE_ALERTAS_EVENTO_BAJA_ERROR = 'DELETE_ALERTAS_EVENTO_BAJA_ERROR';

//DELETE Alertas Volatilidad Baja
export const DELETE_ALERTAS_VOLATILIDAD_BAJA_REQUEST = 'DELETE_ALERTAS_VOLATILIDAD_BAJA_REQUEST';
export const DELETE_ALERTAS_VOLATILIDAD_BAJA_RECEIVE = 'DELETE_ALERTAS_VOLATILIDAD_BAJA_RECEIVE';
export const DELETE_ALERTAS_VOLATILIDAD_BAJA_ERROR = 'DELETE_ALERTAS_VOLATILIDAD_BAJA_ERROR';

//PUT Alertas estatus
export const PUT_ALERTAS_ESTATUS_REQUEST = 'PUT_ALERTAS_ESTATUS_REQUEST';
export const PUT_ALERTAS_ESTATUS_RECEIVE = 'PUT_ALERTAS_ESTATUS_RECEIVE';
export const PUT_ALERTAS_ESTATUS_ERROR = 'PUT_ALERTAS_ESTATUS_ERROR';

//GET Cap Emisora Detalle
export const GET_CAP_EMISORA_DETALLE_REQUEST = 'GET_CAP_EMISORA_DETALLE_REQUEST';
export const GET_CAP_EMISORA_DETALLE_RECEIVE = 'GET_CAP_EMISORA_DETALLE_RECEIVE';
export const GET_CAP_EMISORA_DETALLE_ERROR = 'GET_CAP_EMISORA_DETALLE_ERROR';

export const GET_SERVICIOS_REQUEST = 'GET_SERVICIOS_REQUEST';
export const GET_SERVICIOS_RECEIVE = 'GET_SERVICIOS_RECEIVE';
export const GET_SERVICIOS_ERROR = 'GET_SERVICIOS_ERROR';

export const PUT_SERVICIOS_REQUEST = 'PUT_SERVICIOS_REQUEST';
export const PUT_SERVICIOS_RECEIVE = 'PUT_SERVICIOS_RECEIVE';
export const PUT_SERVICIOS_ERROR = 'PUT_SERVICIOS_ERROR';
// Cancelar orden
export const POST_CANCELA_ORDEN_REQUEST = 'POST_CANCELA_ORDEN_REQUEST';
export const POST_CANCELA_ORDEN_RECEIVE = 'POST_CANCELA_ORDEN_RECEIVE';
export const POST_CANCELA_ORDEN_ERROR = 'POST_CANCELA_ORDEN_ERROR';

//GET Ordenes Cap Estatus
export const GET_ORDENES_CAP_ESTATUS_REQUEST = 'GET_ORDENES_CAP_ESTATUS_REQUEST';
export const GET_ORDENES_CAP_ESTATUS_RECEIVE = 'GET_ORDENES_CAP_ESTATUS_RECEIVE';
export const GET_ORDENES_CAP_ESTATUS_ERROR = 'GET_ORDENES_CAP_ESTATUS_ERROR';

//Este action type es para RESETEAR todos los reducers/estados que tienen esta action al initial state
export const RESET_STATE = "RESET_STATE";

//para RESETEAR estados/reducers especificos, relacionados con los componentes que usan varios estados a la vez
export const RESET_STATE_OPERACIONES_FONDOS = "RESET_STATE_OPERACIONES_FONDOS";
    /*
        RESET_STATE_OPERACIONES_FONDOS resetea estos reducers:
            - fondosCpaEmisReducer
            - fondosCpaGetReducer
            - fondosCpaPutReducer
            - fondosVtaGetReducer
            - fondosVtaPutReducer
    */
export const RESET_STATE_TARJETA_FOLIO = "RESET_STATE_TARJETA_FOLIO";
    /*
        RESET_STATE_TARJETA_FOLIO resetea estos reducers:
            - folioDataReducer
            - posicionFolioReducer
    */
export const RESET_STATE_GET_ORDENES = "RESET_STATE_GET_ORDENES";
    /*
        RESET_STATE_GET_ORDENES resetea estos reducers:
            - ordenesReducer
            - getOrdenesCapEstatusReducer
    */
export const RESET_STATE_MODIF_CANCEL_ORDENES = "RESET_STATE_MODIF_CANCEL_ORDENES";
    /*
        RESET_STATE_MODIF_CANCEL_ORDENES resetea estos reducers:
            - editOrdenReducer
            - postCancelaOrdenReducer
    */
export const RESET_STATE_INFO_EMISORA = "RESET_STATE_INFO_EMISORA";
    /*
        RESET_STATE_INFO_EMISORA resetea estos reducers:
            - infoEmisoraReducer
    */
// GET config de resumen de mercado
export const GET_RESUMEN_MERCADO_REQUEST = 'GET_RESUMEN_MERCADO_REQUEST';
export const GET_RESUMEN_MERCADO_RECEIVE = 'GET_RESUMEN_MERCADO_RECEIVE';
export const GET_RESUMEN_MERCADO_ERROR = 'GET_RESUMEN_MERCADO_ERROR';

// POST config de vector analisis
export const POST_CONFIG_VA_REQUEST = 'POST_CONFIG_VA_REQUEST';
export const POST_CONFIG_VA_RECEIVE = 'POST_CONFIG_VA_RECEIVE';
export const POST_CONFIG_VA_ERROR = 'POST_CONFIG_VA_ERROR';

// POST config de todos los switches de vector analisis
export const POST_ALL_CONFIG_VA_REQUEST = 'POST_ALL_CONFIG_VA_REQUEST';
export const POST_ALL_CONFIG_VA_RECEIVE = 'POST_ALL_CONFIG_VA_RECEIVE';
export const POST_ALL_CONFIG_VA_ERROR = 'POST_ALL_CONFIG_VA_ERROR';

// POST config de resumen de mercado
export const POST_RESUMEN_MERCADO_REQUEST = 'POST_RESUMEN_MERCADO_REQUEST';
export const POST_RESUMEN_MERCADO_RECEIVE = 'POST_RESUMEN_MERCADO_RECEIVE';
export const POST_RESUMEN_MERCADO_ERROR = 'POST_RESUMEN_MERCADO_ERROR';

//GET Alertas Mi Posicion
export const GET_ALERTAS_MI_POSICION_REQUEST = 'GET_ALERTAS_MI_POSICION_REQUEST';
export const GET_ALERTAS_MI_POSICION_RECEIVE = 'GET_ALERTAS_MI_POSICION_RECEIVE';
export const GET_ALERTAS_MI_POSICION_ERROR = 'GET_ALERTAS_MI_POSICION_ERROR';

//PUT Alertas Mi Posicion
export const PUT_ALERTAS_MI_POSICION_REQUEST = 'PUT_ALERTAS_MI_POSICION_REQUEST';
export const PUT_ALERTAS_MI_POSICION_RECEIVE = 'PUT_ALERTAS_MI_POSICION_RECEIVE';
export const PUT_ALERTAS_MI_POSICION_ERROR = 'PUT_ALERTAS_MI_POSICION_ERROR';

export const RESET_STATE_ALERTAS_MI_POSICION = 'RESET_STATE_ALERTAS_MI_POSICION';
/*
    RESET_STATE_ALERTAS_MI_POSICION resetea estos reducers y 
    los pone con su initialState, es decir, estado vacio:
    - getAlertasMiPosicionReducer
    - putAlertasMiPosicionReducer
*/

//GET Alertas Mi Posicion
export const GET_PERMISOS_REQUEST = 'GET_PERMISOS_REQUEST';
export const GET_PERMISOS_RECEIVE = 'GET_PERMISOS_RECEIVE';
export const GET_PERMISOS_ERROR = 'GET_PERMISOS_ERROR';
export const GET_PERMISOS_RESET = 'GET_PERMISOS_RESET';

// GET listas en las que sale una emisora
export const GET_ISSUER_LISTS_REQUEST = 'GET_ISSUER_LISTS_REQUEST';
export const GET_ISSUER_LISTS_RECEIVE = 'GET_ISSUER_LISTS_RECEIVE';
export const GET_ISSUER_LISTS_ERROR = 'GET_ISSUER_LISTS_ERROR';

//Ultima lista vista por el usuario
export const PUT_LIST_ULTIMA_REQUEST = "PUT_ULTIMA_REQUEST";
export const PUT_LIST_ULTIMA_RECEIVE = "PUT_ULTIMA_RECEIVE";
export const PUT_LIST_ULTIMA_ERROR = "PUT_ULTIMA_ERROR";

// PUT config de todos los switches de vector analisis
export const PUT_SERVICIO_REQUEST = 'PUT_SERVICIO_REQUEST';
export const PUT_SERVICIO_RECEIVE = 'PUT_SERVICIO_RECEIVE';
export const PUT_SERVICIO_ERROR = 'PUT_SERVICIO_ERROR';